# -*- coding: utf-8 -*-
"""Multiple Linear Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11SVpWGoE16DL28TpefmgDPx6QQJNHCW8

# Multiple Linear Regression

Importing Libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""Import data"""

dataset=pd.read_csv('50_Startups.csv')
#All columns except last column- dependent variables
X = dataset.iloc[:, :-1].values
#Depent variable last column
y = dataset.iloc[:, -1].values

print(X)

"""Encoding Categorical data"""

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
#encoding states column
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

print(X)

"""Split into train and test set"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

"""Training Multiple linear regression model"""

from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)

"""Predicting Results"""

y_pred=regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))