# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GLIyA_OXJWzTey1nIz5cGQ_qSQ_-1ZHr

#**Polynomial Regression**

Importing Libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""Importing Dataset"""

dataset=pd.read_csv('Position_Salaries.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

"""Train linear regression"""

from sklearn.linear_model import LinearRegression
lin_reg=LinearRegression()
lin_reg.fit(X,y)

"""Train Polynomial Regression"""

#y=b0+b1x1+b2(x1^2)+......+bn(x1^n)  <- polynomialregression
#hence we need to create a matrix of features containing x1,x1^2...,x1^n
from sklearn.preprocessing import PolynomialFeatures
poly_reg=PolynomialFeatures(degree=4)
X_poly=poly_reg.fit_transform(X)
#now apply linear regression to x_poly and y
from sklearn.linear_model import LinearRegression
lin_reg_2=LinearRegression()
lin_reg_2.fit(X_poly,y)

"""Visualize Linear Regression"""

plt.scatter(X,y,color='pink')
plt.plot(X,lin_reg.predict(X),color='blue')
plt.title('Linear Reg')
plt.xlabel('position')
plt.ylabel('salary')
plt.show()

"""Visualize Polynomial Regression"""

plt.scatter(X,y,color='pink')
plt.plot(X,lin_reg_2.predict(X_poly),color='blue')
plt.title('Poly Reg')
plt.xlabel('position')
plt.ylabel('salary')
plt.show()

"""Predict Single value -Linear Regression"""

#parameter required is a 2 d array hence double brackets
lin_reg.predict([[6.5]])

"""Predict Single value -Poly Regression"""

lin_reg_2.predict(poly_reg.fit_transform([[6.5]]))